/**
 * API Types (Auto-Generated)
 * ===========================
 * 
 * This file contains TypeScript types that are automatically generated from
 * a JSON schema that defines the API contract between the frontend and backend.
 * 
 * IMPORTANT: DO NOT MANUALLY EDIT THIS FILE!
 * 
 * These types are generated by a build tool (e.g., quicktype, json-schema-to-typescript)
 * and will be overwritten on the next generation run.
 * 
 * Usage:
 * - Import these types in api.ts service methods to ensure type safety
 * - Use these types when making API requests/responses
 * - Reference these types in your application code when working with API data
 * 
 * Example:
 *   import { UserResponse, CreateResourceRequest } from './types/api.types';
 *   
 *   async exampleCreateResource(data: CreateResourceRequest): Promise<UserResponse> {
 *     return this.post('/v1/resources', data);
 *   }
 * 
 * To regenerate these types:
 * 1. Update the JSON schema file (typically in schema/ directory)
 * 2. Run the type generation command (e.g., npm run generate-types)
 * 3. This file will be automatically updated
 * 
 * The JSON schema serves as the single source of truth for API contracts,
 * ensuring consistency between frontend and backend type definitions.
 */

// Auto-generated types will appear below this comment
// Generation timestamp: [Will be added by generator]
